Rolpo.UI/Controllers/Lookup/LookupController.cs
using System.Web.Mvc;

namespace Rolpo.UI.Controllers
{
    /// <summary>
    ///  Master entry Controller
    /// </summary>
    /// 

    [Authorize]
    //[RequireHttps]
    public class LookupController : Controller
    {
        
        
        public LookupController()
        {
        }
         
	 
        public ActionResult MediaTypes()
        {
            return View();
        }
     
	 
        // <summary>
        /// Email Formats
        /// </summary>
        /// <returns></returns>
        public ActionResult EmailFormat()
        {
            return View();
        }

    
        /// <summary>
        /// Nlog Entries
        /// </summary>
        /// <returns></returns>
        public ActionResult LogEntries()
        {
            return View();
        }

        /// <summary>
        /// Status
        /// </summary>
        /// <returns></returns>
        public ActionResult Status() {
            return View();
        }

        /// <summary>
        ///  TRainee Level
        /// </summary>
        /// <returns></returns>
        public ActionResult TraineeLevel()
        {
            return View();
        }

        /// <summary>
        ///  CourseCategory
        /// </summary>
        /// <returns></returns>
        public ActionResult CourseCategory()
        {
            return View();
        }

        /// <summary>
        ///  CourseLevel
        /// </summary>
        /// <returns></returns>
        public ActionResult CourseLevel()
        {
            return View();
        }


        /// <summary>
        ///  CoursePeriodType
        /// </summary>
        /// <returns></returns>
        public ActionResult CoursePeriodType()
        {
            return View();
        }


    }


}

Rolpo.UI/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rolpo.UI.Controllers
{
    [Authorize]
    public class MembersController : Controller
    {
        // GET: Members
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Trainee()
        {
            return View();
        }
        public ActionResult Trainer()
        {
            return View();
        }

        public ActionResult Coordinators()
        {
            return View();
        }

        public ActionResult AsstCoordinators()
        {
            return View();
        }

        public ActionResult SaveUploadedFile()
        {

            bool isSavedSuccessfully = true;
            string fName = "";
            string fullPath = "";
            string pathW;
            string webImagePath = "~/Images/Members";
           


            if (!System.IO.Directory.Exists(Server.MapPath(webImagePath)))
            {
                System.IO.Directory.CreateDirectory(Server.MapPath(webImagePath));
            }

            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];

                fName = file.FileName;
                if (file != null && file.ContentLength > 0)
                {
                    fName = fName.Replace(" ", "_");
                    fName = fName.Insert(fName.IndexOf("."), DateTime.Now.ToString("_ddMMyyhhmmss"));
                    pathW = Path.Combine(Server.MapPath(webImagePath), fName);
                    file.SaveAs(pathW);
                    fullPath = webImagePath + "/" + fName;
                    isSavedSuccessfully = true;
                }

            }
            if (isSavedSuccessfully)
            {

                return Json(new { Message = "ok", ImagePath = fullPath });
            }
            else
            {
                return Json(new { Message = "Error in saving file" });
            }
        }

        /// <summary>
        /// remove image file
        /// </summary>
        /// <returns></returns>
        public string RemoveFile([System.Web.Http.FromUri]string filePath = "")
        {

            string baseUrl = System.Web.Configuration.WebConfigurationManager.AppSettings["baseUrl"];
            string ImagePath = Server.MapPath(filePath.Replace(baseUrl, "~/"));

           
                try
                {
                    if (System.IO.File.Exists(ImagePath))
                    {
                        System.IO.File.Delete(ImagePath);
                    }
                    return "ok";
                }
                catch (Exception ex)
                {
                    return "error";
                }
           

            //for files not having path saved in database            

        }
    }
}

Rolpo.UI/Controllers/ReportController.cs
using ClosedXML.Excel;
using Rolpo.Model;
using Rolpo.Service;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Web.Mvc;
using System;

namespace Rolpo.UI.Controllers
{
    public class ReportController : Controller
    {
        IBatchTraineeService _batchtraineeService;
        IBatchService _batchService;

        public ReportController(IBatchTraineeService batchtraineeService, IBatchService batchService)
        {
            _batchtraineeService = batchtraineeService;
            _batchService = batchService;
        }
        // GET: Batch
        public ActionResult Batches()
        {
            return View();
        }

        public ActionResult ListOfTrainees()
        {
            return View();
        }

        [HttpGet]
        public void ExportTraineeListToExcel(BatchTraineeViewModel_Input input)
        {

            List<DTObject> DTList = new List<DTObject>()
            {
                new DTObject{ServerObjectName="TraineeName",DisplayName="Trainee Name",DataTypeName=""},
                //new DTObject{ServerObjectName="JoinedDate",DisplayName="Joined On",DataTypeName=""},
                  new DTObject{ServerObjectName="BatchCode",DisplayName="Batch Code",DataTypeName=""},
                  new DTObject{ServerObjectName="BatchName",DisplayName="Batch Name",DataTypeName=""},
                    //new DTObject{ServerObjectName="CourseCode",DisplayName="Course Code",DataTypeName=""},
                    //new DTObject{ServerObjectName="CourseFullName",DisplayName="Course Name",DataTypeName=""},
                  new DTObject{ServerObjectName="TraineeLevelName",DisplayName="Trainee Level",DataTypeName=""},
                  new DTObject{ServerObjectName="Position",DisplayName="Position",DataTypeName=""},
                  new DTObject{ServerObjectName="CompanyName",DisplayName="Company Name",DataTypeName=""},
                  new DTObject{ServerObjectName="Department",DisplayName="Department",DataTypeName=""},
                  new DTObject{ServerObjectName="BatchStartDateLOCAL",DisplayName="Batch Start Date",DataTypeName=""},
                  new DTObject{ServerObjectName="BatchEndDateLOCAL",DisplayName="Batch End Date",DataTypeName=""},
                  new DTObject{ServerObjectName="Duration",DisplayName="Duration",DataTypeName=""}
              };


            DataTable dt = new DataTable();

            input.ShowAll = 1;
            IEnumerable<BatchTraineeReportViewModel> arr =
                _batchtraineeService.GetBatchTraineeForReport(userId: null
                , input: input);

            dt = Rolpo.UI.FileManagerExtensions.CopyToDataTable<BatchTraineeReportViewModel>(arr, DTList);
            ExportDataTableToExcel(dt, new ExcelReportProperties()
            {
                CompanyName = "NEA - Learning Management System",
                CompanyAddressLine = "Kharipati, Bhaktapur",
                ReportTitle = "Trainee_Report"

            });


        }

        [HttpGet]
        public void ExportBatchListToExcel(BatchViewModel_Input input)
        {

            List<DTObject> DTList = new List<DTObject>()
            {
                new DTObject{ServerObjectName="BatchCode",DisplayName="Batch Code",DataTypeName=""},
                new DTObject{ServerObjectName="BatchName",DisplayName="Batch Name",DataTypeName=""},
                new DTObject{ServerObjectName="CourseCode",DisplayName="Course Code",DataTypeName=""},
                new DTObject{ServerObjectName="CourseFullName",DisplayName="Course Name",DataTypeName=""},
                new DTObject{ServerObjectName="LevelName",DisplayName="Course Level",DataTypeName=""},
                new DTObject{ServerObjectName="BatchStartDateLOCAL",DisplayName="Batch Start Date",DataTypeName=""},
                new DTObject{ServerObjectName="BatchEndDateLOCAL",DisplayName="Batch End Date",DataTypeName=""},
                new DTObject{ServerObjectName="Coordinator",DisplayName="Batch Coordinator",DataTypeName=""},
                new DTObject{ServerObjectName="ASSCoordinator",DisplayName="Assistant Coordinator",DataTypeName=""},
                new DTObject{ServerObjectName="Duration",DisplayName="Course Duration",DataTypeName=""},
                new DTObject{ServerObjectName="TrainingAddress",DisplayName="Training Address",DataTypeName=""},
                new DTObject{ServerObjectName="TotalTrainees",DisplayName="# of Trainees",DataTypeName=""}
             };


            DataTable dt = new DataTable();

            input.ShowAll = 1;
            IEnumerable<BatchReportViewModel> arr =
                _batchService.GetBatchForReport(userId: null
                , input: input);

            dt = Rolpo.UI.FileManagerExtensions.CopyToDataTable<BatchReportViewModel>(arr, DTList);
            ExportDataTableToExcel(dt, new ExcelReportProperties()
            {
                CompanyName = "NEA - Learning Management System",
                CompanyAddressLine = "Kharipati, Bhaktapur",
                ReportTitle = "Batch_Report"

            });




        }

        //Export to excel
        private void ExportDataTableToExcel(DataTable dt, ExcelReportProperties property)
        {

            using (XLWorkbook wb = new XLWorkbook())
            {
                var ws = wb.Worksheets.Add(dt, property.ReportTitle);
                var listOfStrings = new List<String>();
                int columns = Convert.ToInt16((dt.Columns.Count) / 2);
                if (columns < 3) { columns = 4; }
                ws.Row(1).InsertRowsAbove(4);

                ws.Cell(1, 1).Value = property.CompanyName + " " + "," + " " + property.CompanyAddressLine;
                ws.Cell(1, 1).Style.Font.FontColor = XLColor.DarkBlue;
                ws.Cell(1, 1).Style.Font.FontSize = 18;

                if (!string.IsNullOrEmpty(property.ReportTitle))
                {
                    ws.Cell(3, 1).Value = property.ReportTitle;
                    ws.Cell(3, 1).Style.Font.FontColor = XLColor.Black;

                }

                ws.Cell(3, columns - 1).Value = "Generated on " + DateTime.Today.ToShortDateString();
                ws.Cell(3, columns - 1).Style.Font.FontColor = XLColor.Black;

                string myName = Server.UrlEncode(property.ReportTitle + "_" +
                DateTime.Now.ToShortDateString().Replace("/", "_") + ".xlsx");
                MemoryStream stream = GetStream(wb);// The method is defined below
                Response.Clear();
                Response.Buffer = true;
                Response.AddHeader("content-disposition",
                "attachment; filename=" + myName);
                Response.ContentType = "application/vnd.ms-excel";
                Response.BinaryWrite(stream.ToArray());
                Response.End();
            }
        }

        private MemoryStream GetStream(XLWorkbook wb)
        {
            MemoryStream fs = new MemoryStream();
            wb.SaveAs(fs);
            fs.Position = 0;
            return fs;
        }
    }
}

Rolpo.UI/Views/Shared/_Layout.cshtml
@using Rolpo.UI
<!DOCTYPE html>
<html data-ng-app="RolpoApp">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewData["Title"] :: A product of Rolpo Tech</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link href="~/theme/adminlte2.4.3/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="~/theme/adminlte2.4.3/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link href="~/theme/adminlte2.4.3/Ionicons/css/ionicons.min.css" rel="stylesheet" />
    <!-- jvectormap -->
    <link href="~/theme/adminlte2.4.3/jvectormap/jquery-jvectormap.css" rel="stylesheet" />
    <!-- Theme style -->
    <link href="~/theme/adminlte2.4.3/css/AdminLTE.css" rel="stylesheet" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="~/theme/adminlte2.4.3/css/skins/_all-skins.css" rel="stylesheet" />

    <style type="text/css">
        [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {
            display: none !important;
        }
    </style>

    @RenderSection("css", required: false)


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">


</head>
<body class="hold-transition skin-blue sidebar-mini" ng-cloak>
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index", "Dashboard")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>LMS</b></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>LMS</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            @Html.Partial("_LoginPartial")
                        </li>

                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/images/user.png" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <text>@UserRights.FullName()</text>
                            }
                            else
                            { <span>Please login!</span> }
                        </p>

                        <a href="/Manage/Index"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">MAIN NAVIGATION</li>
                    @Html.Partial("~/Views/Shared/_Menus.cshtml")
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        @RenderBody()
        <!-- /.content-wrapper -->
        <footer class="main-footer">
           
            <strong>Copyright &copy;2018 </strong> <b> DuMoR Technologies</b>
        </footer>



    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->
    <script src="~/theme/adminlte2.4.3/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    
    <script src="~/theme/adminlte2.4.3/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="~/theme/adminlte2.4.3/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="~/theme/adminlte2.4.3/js/adminlte.min.js"></script>
    <!-- Sparkline -->
    <script src="~/theme/adminlte2.4.3/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
    <!-- jvectormap  -->


    <script type="text/javascript">
		var serviceBase = '@System.Configuration.ConfigurationManager.AppSettings["baseUrl"].ToString()'
    </script>


    <script src="~/lib/angular/angular.min.js"></script>
    <script src="~/lib/angular-sanitize/angular-sanitize.min.js"></script>
    <script src="~/lib/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>

    <script src="~/js/app.js"></script>

    <script type="text/javascript">
		var baseUrl = '@System.Configuration.ConfigurationManager.AppSettings["baseUrl"].ToString()' @*'@SessionExtensions.Current.organization.ServiceBaseUrl';*@
		$(document).ready(function () {
			//Set Menus
			$('[data-classid]').removeClass('active');
			$('[data-classid="@ViewBag.Current"]').addClass('active').closest("li.treeview").addClass('active');
			$('[data-classid="@ViewBag.Current"]').parent().parent().addClass('active');
		});

    </script>

    <script type="text/ng-template" id="customModalPopup">
        @{Html.RenderPartial("~/views/shared/_Modal.cshtml");}
    </script>


    @RenderSection("scripts", required: false)


</body>
</html>

Rolpo.UI/Views/Shared/_Menus.cshtml
@if (UserRights.IsCoordinator())
{
	<li class="treeview" data-classId="Admin_Courses">
		<a href="javascript:void(0);">
			<i class="fa  fa-book"></i> <span>Courses</span>
			<i class="fa fa-angle-left pull-right"></i>
		</a>
		<ul class="treeview-menu">
			<li data-classId="Admin_Courses_Summary"><a href="~/Courses/Index" title="Courses Summary"><i class="fa fa-bars"></i>Summary</a></li>
		</ul>
	</li>
	<li class="treeview" data-classId="Admin_Members">
		<a href="javascript:void(0);">
			<i class="fa fa-group"></i> <span>Members</span>
			<i class="fa fa-angle-left pull-right"></i>
		</a>
		<ul class="treeview-menu">
            <li data-classId="Admin_Members_Coordinators"><a href="@Url.Action("Coordinators","Members")" title="Coordinators Summary"><i class="fa fa-object-group"></i>Coordinators</a></li>
            <li data-classId="Admin_Members_AsstCoordinators"><a href="@Url.Action("AsstCoordinators","Members")" title="Assistant Coordinators Summary"><i class="fa fa-eye"></i>Assistant Coordinators</a></li>
			<li data-classId="Admin_Members_Trainees"><a href="@Url.Action("Trainee","Members")" title="Trainees Summary"><i class="fa fa-group"></i>Trainees</a></li>
			<li data-classId="Admin_Members_Trainers"><a href="@Url.Action("Trainer","Members")" title="Trainers Summary"><i class="fa fa-bullhorn"></i>Trainers</a></li>
            
           
            
		</ul>
	</li>
	<li class="treeview" data-classId="Admin_Batches">
		<a href="javascript:void(0);">
			<i class="fa  fa-graduation-cap"></i> <span>Batches</span>
			<i class="fa fa-angle-left pull-right"></i>
		</a>
		<ul class="treeview-menu">
			<li data-classId="Admin_Batches_Summary"><a href="~/Batch/Index" title="Batches Summary"><i class="fa fa-bars"></i>Summary</a></li>
		</ul>
	</li>
	<li class="treeview" data-classId="Admin_Reports">
		<a href="javascript:void(0);">
			<i class="fa   fa-file-excel-o"></i> <span>Reports</span>
			<i class="fa fa-angle-left pull-right"></i>
		</a>
		<ul class="treeview-menu">
			<li data-classId="Admin_Reports_Batches"><a href="@Url.Action("Batches","Report")" title="Batches Report"><i class="fa  fa-file-excel-o"></i>Batches</a></li>
			<li data-classId="Admin_Reports_TraineesList"><a href="@Url.Action("ListOfTrainees","Report")" title="Trainees List Report"><i class="fa  fa-file-excel-o"></i>Trainees Per Batch</a></li>
		</ul>
	</li>
	<li class="treeview" data-classId="Settings">
		<a href="javascript:void(0);">
			<i class="fa  fa-gear"></i> <span>Adminstration</span>
			<i class="fa fa-angle-left pull-right"></i>
		</a>
		<ul class="treeview-menu">
			<li data-classId="Settings_Organization"><a href="@Url.Action("Organization","Home")" title="Organiation Information"><i class="fa fa-industry"></i>Organization</a></li>
			<li data-classId="Settings_Account"><a alt="User List" href="@Url.Action("UserList","Manage")" title="Add Edit Users"><i class="fa fa-users"></i> Users </a></li>
			@if (UserRights.IsSuperAdmin())
			{
				<li data-classId="Settings_Course"><a href="@Url.Action("CourseCategory", "Lookup")" title="Categories and Sub categories"><i class="fa fa-cubes"></i>Categories</a></li>
				<li data-classId="Settings_CourseLevels"><a href="@Url.Action("CourseLevel", "Lookup")" title="Course levels"><i class="fa  fa-calculator"></i>Course Levels</a></li>
				<li data-classId="Settings_TraineeLevels"><a href="@Url.Action("TraineeLevel", "Lookup")" title="Media Types"><i class="fa fa-bullseye"></i>Trainee Level</a></li>
				 
					<li data-classId="Settings_Status"><a href="@Url.Action("Status", "Lookup")" title="Status"><i class="fa fa-check-square-o"></i>Status</a></li>
					<li data-classId="Settings_CoursePeriodType"><a href="@Url.Action("CoursePeriodType", "Lookup")" title="Period Types"><i class="fa fa-clock-o"></i>Period Types</a></li>
					<li data-classId="Settings_MediaTypes"><a href="@Url.Action("MediaTypes", "Lookup")" title="Media Types"><i class="fa fa-file-video-o"></i>Media Types</a></li>
 
			}

		</ul>
	</li>
}

Rolpo.UI/Views/Shared/_Modal.cshtml
<div class="modal-header">
	<h3>{{modalOptions.headerText}}</h3>
</div>
<div class="modal-body">
	<p ng-bind-html="modalOptions.bodyText| unsafe"></p>
</div>
<div class="modal-footer">
	<button type="button" class="btn flat"
			data-ng-click="modalOptions.close()">
		{{modalOptions.closeButtonText}}
	</button>
	<button class="btn btn-primary flat"
			data-ng-click="modalOptions.ok();">
		{{modalOptions.actionButtonText}}
	</button>
</div>